### ISSUE TITLE
Doesn't handle non-US characters

### ISSUE THREAD

**Issue by tomsoderlund** [mlcamilli/trello-export#1]
```
prompt$ python trello-export.py myproject.json 
Traceback (most recent call last):
  File "trello-export.py", line 76, in <module>
    main()
  File "trello-export.py", line 12, in main
    print_cards(json_object, args.outputfile)
  File "trello-export.py", line 69, in print_cards
    card['desc'], checklist_data(card), labels(card), card['due'], members(card)]) 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-17: ordinal not in range(128)
```

I'll try to fix it if I have time.

Thanks for a great script! I could workaround this issue by search/replace in the json file.

**Comment by mlcamilli** [comment]
yea I can put a fix in for it, I have actually a rather large update that I'll be uploading soon

**Comment by mlcamilli** [comment]
fixed! adding more functionality here soon
